repos:
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: check-added-large-files
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: poetry run pylint georelate/ tests/
          language: system
          always_run: true
          pass_filenames: false
